### ISSUE TITLE
Add About Screen

### ISSUE THREAD

**Issue by joneldominic** [joneldominic/personal-finance-management-app#72]
- [ ] Add the following paragraph

> An open-source, free budgeting app inspired by a popular apps, like Wallet, Splitwise and Buckets. Designed to provide an easy-to-use solution for managing personal finances. The app allows users to categorize expenses, set budgets, and track spending, as well as reach savings goals. With a user-friendly interface, this app is perfect for individuals looking to take control of their finances.

- [ ] Add Github repository link

**Comment by sanchitpasricha** [comment]
Hi would you assign this issue to me and what are your requirements ?

**Comment by joneldominic** [comment]
Sure, I'll get back to you once I'm done adding a mock-up for this one. Thanks.

**Comment by joneldominic** [comment]
Hello @sanchitpasricha , I just added a mock-up for About Screen ([Figma](https://www.figma.com/file/Xf0d1yWHngbCS9hI8qwtmB/Personal-Finance-Management-App?node-id=0%3A1)).
